version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    assignees:
      - "pixidream"
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
    assignees:
      - "pixidream"
