FROM node:lts-alpine3.19

WORKDIR /srv/frontend
RUN apk update

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY . .

RUN pnpm install

EXPOSE 3000

CMD ["pnpm", "run", "dev", "--host=0.0.0.0"]