version: "3"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev

    volumes:
      - "./backend:/pb"

    ports:
      - "8080:8080"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev

    volumes:
      - "./frontend:/srv/frontend"

    ports:
      - "3000:3000"
