# Builder stage
FROM golang:1.22.1-alpine3.19 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main .

# Final stage
FROM alpine:3.19 as runtime

WORKDIR /root/
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main", "serve", "--http=0.0.0.0:8080"]
