FROM golang:1.22.1-alpine3.19

RUN apk update && apk add --no-cache unzip ca-certificates

WORKDIR /pb
COPY ["main.go", "go.mod", "go.sum", "./"]

EXPOSE 8080

CMD ["go", "run", "/pb/main.go", "serve", "--http=0.0.0.0:8080"]
