name: Run Deploy Script via SSH

on:
  push:
    branches:
      - main
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: pull release branch and rebuild / restart container
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          LOG_FILE="deployment_${TIMESTAMP}.txt"
          ssh -o "StrictHostKeyChecking=no" -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'bash -s' < ./scripts/deploy.sh | tee "/home/pixi/creamrobotics_deploy_logs/$LOG_FILE"
